# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z045ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.cache/wt [current_project]
set_property parent.project_path C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zc706:part0:1.3 [current_project]
set_property ip_repo_paths c:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports [current_project]
set_property ip_output_repo c:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/generic_dpram.v
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/timescale.v
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/generic_fifo_dc_gray.v
}
read_vhdl -library work {
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/saturn_numeric_pkg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/saturn_dog_pkg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/saturn_numeric_pkg-body.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/saturn_dog_pkg-body.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/dual_clk_fifo_pkg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/dual_clk_fifo.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/xy_delay_pkg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/xy_delay.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/shift_reg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/subsample_pkg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/subsample.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/saturn_search_pkg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/math_real.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/gradient_tarek.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/gradient_pkg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/gaussian_filter_pkg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/gaussian_filter.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/saturn_search_pkg-body.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/pyramid_pkg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/pyramid.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/max_2_xv.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/math_real_body.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/dpram_pkg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/dpram.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/dog_pkg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/dog.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/delay_pkg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/delay.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/sort_pkg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/sort.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/search_pkg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/search.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/pyramid_dog_pkg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/pyramid_dog.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/extractor_pkg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/extractor.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/xy_to_axis.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/rgb_to_gs_pkg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/pyramid_kp_pkg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/pyramid_kp.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/axis_xy_pkg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/axis_to_xy.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/addr_dec_pkg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/addr_dec.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/user_logic.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/work/axis_pyramid_kp.vhd
}
read_vhdl -library proc_common_v3_00_a {
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/proc_common_v3_00_a/proc_common_pkg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/proc_common_v3_00_a/family_support.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/proc_common_v3_00_a/pselect_f.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/proc_common_v3_00_a/ipif_pkg.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/proc_common_v3_00_a/counter_f.vhd
}
read_vhdl -library axi_lite_ipif_v1_01_a {
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/axi_lite_ipif_v1_01_a/address_decoder.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/axi_lite_ipif_v1_01_a/slave_attachment.vhd
  C:/Users/frede/OneDrive/Documents/fred_projet/pyramid_prj/pyramid.srcs/sources_1/imports/axi_lite_ipif_v1_01_a/axi_lite_ipif.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top axis_pyramid_kp -part xc7z045ffg900-2


write_checkpoint -force -noxdef axis_pyramid_kp.dcp

catch { report_utilization -file axis_pyramid_kp_utilization_synth.rpt -pb axis_pyramid_kp_utilization_synth.pb }
