#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Jul 10 12:25:49 CEST 2026
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim TEST_OREC_behav -key {Behavioral:sim_1:Functional:TEST_OREC} -tclbatch TEST_OREC.tcl -view /home/demelo/vivado_prjs/testbench_eads/test_orec_cody/TEST_OREC_behav.wcfg -log simulate.log"
xsim TEST_OREC_behav -key {Behavioral:sim_1:Functional:TEST_OREC} -tclbatch TEST_OREC.tcl -view /home/demelo/vivado_prjs/testbench_eads/test_orec_cody/TEST_OREC_behav.wcfg -log simulate.log

