#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Jul 02 13:37:35 CEST 2026
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L work -L secureip --snapshot TEST_PYRAMID_func_synth work.TEST_PYRAMID -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L work -L secureip --snapshot TEST_PYRAMID_func_synth work.TEST_PYRAMID -log elaborate.log

