#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jul 02 13:37:39 CEST 2026
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim TEST_PYRAMID_func_synth -key {Post-Synthesis:sim_1:Functional:TEST_PYRAMID} -tclbatch TEST_PYRAMID.tcl -view /home/demelo/vivado_prjs/testbench_eads/test_gradient/TEST_PYRAMID_behav.wcfg -log simulate.log"
xsim TEST_PYRAMID_func_synth -key {Post-Synthesis:sim_1:Functional:TEST_PYRAMID} -tclbatch TEST_PYRAMID.tcl -view /home/demelo/vivado_prjs/testbench_eads/test_gradient/TEST_PYRAMID_behav.wcfg -log simulate.log

