# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/demelo/vivado_prjs/testbench_eads/test_orec_cody/test_orec.srcs/sources_1/ip/dp_grad/dp_grad.xci
# IP: The module: 'dp_grad' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/demelo/vivado_prjs/testbench_eads/test_orec_cody/test_orec.gen/sources_1/ip/dp_grad/dp_grad_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dp_grad'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/demelo/vivado_prjs/testbench_eads/test_orec_cody/test_orec.srcs/sources_1/ip/dp_grad/dp_grad.xci
# IP: The module: 'dp_grad' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/demelo/vivado_prjs/testbench_eads/test_orec_cody/test_orec.gen/sources_1/ip/dp_grad/dp_grad_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dp_grad'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
