# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.runs/synth_1/gaussian_filter.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z045ffg900-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.cache/wt [current_project]
set_property parent.project_path /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/generic_fifo_dc_gray.v
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/generic_dpram.v
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/timescale.v
}
read_vhdl -library work {
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/saturn_numeric_pkg.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/saturn_numeric_pkg-body.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/math_real.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/math_real_body.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/saturn_dog_pkg.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/saturn_dog_pkg-body.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/dual_clk_fifo_pkg.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/dual_clk_fifo.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/xy_delay_pkg.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/shift_reg.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/gradient_tarek.vhd
  /home/demelo/vivado_prjs/testbench_eads/vhdl/src/orec-II/virtex-II-pro/lr_snml.vhd
  /home/demelo/vivado_prjs/testbench_eads/vhdl/src/orec-II/virtex-II-pro/lr_grad.vhd
  /home/demelo/vivado_prjs/testbench_eads/vhdl/src/orec-II/virtex-II-pro/lr_conv.vhd
  /home/demelo/vivado_prjs/testbench_eads/vhdl/src/orec-II/conv_lig.vhd
  /home/demelo/vivado_prjs/testbench_eads/vhdl/src/orec-II/snml.vhd
  /home/demelo/vivado_prjs/testbench_eads/vhdl/src/orec-II/norm_orie.vhd
  /home/demelo/vivado_prjs/testbench_eads/vhdl/src/orec-II/gradient.vhd
  /home/demelo/vivado_prjs/testbench_eads/vhdl/src/orec-II/biseuillage.vhd
  /home/demelo/vivado_prjs/testbench_eads/vhdl/src/orec-II/ampl.vhd
  /home/demelo/vivado_prjs/testbench_eads/vhdl/src/orec-II/conv_col.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/new/imaging_to_axis.vhd
  /home/demelo/vivado_prjs/testbench_eads/vhdl/tst/divers/resynch_sgnx8.vhd
  /home/demelo/vivado_prjs/testbench_eads/vhdl/tst/divers/writeimg.vhd
  /home/demelo/vivado_prjs/testbench_eads/vhdl/tst/divers/readimg.vhd
  /home/demelo/vivado_prjs/testbench_eads/vhdl/src/orec-II/orec.vhd
  /home/demelo/vivado_prjs/testbench_eads/vhdl/tst/test_orec.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/axis_to_xy.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/xy_to_axis.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/new/lr_grad_tarek.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/new/test_pyramid.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/gaussian_filter_pkg.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/gaussian_filter.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/xy_delay.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/new/xy_delay_fred.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/dog.vhd
  /home/demelo/vivado_prjs/testbench_eads/pyramid_prj/pyramid.srcs/sources_1/imports/work/dog_pkg.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/delay_pkg.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/delay.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/new/xy_delay_cody.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/axis_to_xy_cody.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/work/gradient_cody.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/new/xy_delay_cody2.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/new/gaussian_filter_cody.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/new/lr_gauss_cody.vhd
  /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/imports/Téléchargements/lr_cody.vhd
}
read_ip -quiet /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/ip/dp_conv/dp_conv.xci
set_property used_in_implementation false [get_files -all /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.gen/sources_1/ip/dp_conv/dp_conv_ooc.xdc]

read_ip -quiet /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/ip/dp_grad/dp_grad.xci
set_property used_in_implementation false [get_files -all /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.gen/sources_1/ip/dp_grad/dp_grad_ooc.xdc]

read_ip -quiet /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/ip/dp_snml/dp_snml.xci
set_property used_in_implementation false [get_files -all /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.gen/sources_1/ip/dp_snml/dp_snml_ooc.xdc]

read_ip -quiet /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.srcs/sources_1/ip/dp_grad_tarek/dp_grad_tarek.xci
set_property used_in_implementation false [get_files -all /home/demelo/vivado_prjs/testbench_eads/test_grad_imv/test_grad_imv.gen/sources_1/ip/dp_grad_tarek/dp_grad_tarek_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top gaussian_filter -part xc7z045ffg900-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef gaussian_filter.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file gaussian_filter_utilization_synth.rpt -pb gaussian_filter_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
